# Generated by Django 4.0.6 on 2022-07-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('fk_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('genero', models.CharField(blank=True, default=None, max_length=1)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroASignos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frec_resp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frec_card', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prec_arte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('glicemias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('fk_hospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.hospitalizacion')),
                ('fk_medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('fech_naci', models.DateTimeField(auto_now=True)),
                ('latitud', models.DecimalField(decimal_places=8, default=None, max_digits=10, null=True)),
                ('longitud', models.DecimalField(decimal_places=8, default=None, max_digits=10, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('fk_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='fk_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.persona'),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='fk_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.medico'),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='fk_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.paciente'),
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=255)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastChangeDate', models.DateTimeField(auto_now=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.paciente')),
                ('fk_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.parentesco')),
                ('fk_persona', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hospitalizationApp.persona')),
            ],
        ),
    ]
